version: '3.7'
services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "4000:3000"

  frontend:
    image: node:20
    working_dir: /usr/src/app/frontend
    command: npm install && npm run build
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:14
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
