version: '3.7'
services:
  web:
    build:
      context: .
      target: backend-app
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    env_file:
      - .env.local.template
      - .env.local
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      target: frontend-builder
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3000"

  postgres:
    image: postgres:14
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env.local.template
    ports:
      - "5432:5432"

volumes:
  node_modules:
